[tool.black]
line-length = 100
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.vscode
    | docs
    | _build
    | buck-out
    | build
    | dist
    | assets
    | panel-examples
    | pdm-wheels
  )/
)
'''